/* =============================================== */
/* Plugins Settings for Omnibiz Template           */
/* =============================================== */

/* =============================================== */
/* Table of Content
==================================================

01 Flexslider Home Default
02 Flexslider Home Alternative
03 Project Slider
04 Widget Slide
05 Post Slider
06 Testimonial Slider
07 Work Carousel & Blog Carousel
08 Camera Slider
09 Content Slider
10 Responsive Dropdown Menu
11 Tipsy
12 Works Zoomer
13 Skill Bars
14 Fancybox
15 Google Map for Contact 1
16 Google Map for Contact 2
17 Widget Tabs
18 Responsive Video
19 zFlickrFeed
20 Tweetable
21 Isotope Filtering
22 Vertical Tabs
23 Info Box
24 Portfolio Image Hover
25 Blog Masonry
26 jQuery Countdown & Easy Pie Chart
27 Subscribe Form Validation
28 Contact Form Validation
29 Superfish Menu

/* =============================================== */

//jQuery No Conflict
jQuery.noConflict();
  
//Document Ready
jQuery(document).ready(function($){

  $(window).load(function() { 

  // 01 Flexslider Home Default
  if ($('.flexslider').length && jQuery()) { 
    $('.flexslider').flexslider({
      namespace: "flex-",            //Prefix string attached to the class of every element generated by the plugin       
      animation: "slide",            //Select your animation type, "fade" or "slide"
      easing: "easeInOutExpo",       //Determines the easing method used in jQuery transitions. jQuery easing plugin is supported!
      direction: "horizontal",       //Select the sliding direction, "horizontal" or "vertical"       
      animationLoop: true,           //Should the animation loop? If false, directionNav will received "disable" classes at either end  
      slideshowSpeed: 7000,          //Set the speed of the slideshow cycling, in milliseconds
      animationSpeed: 600,           //Set the speed of animations, in milliseconds       
      pauseOnHover: true,            //Pause the slideshow when hovering over slider, then resume when no longer hovering
      useCSS: false,                 //Slider will use CSS3 transitions if available
      touch: true,                   //Allow touch swipe navigation of the slider on touch-enabled devices
      video: true,                   //If using video in the slider, will prevent CSS3 3D Transforms to avoid graphical glitches
      controlNav: true,              //Create navigation for paging control of each clide? Note: Leave true for manualControls usage
      directionNav: true             //Create navigation for previous/next navigation? (true/false)
    }); 
  }


  // 02 Flexslider Home Alternative
  if ($('.flexslider2').length && jQuery()) {
    $('.flexslider2').flexslider({
      namespace: "flex2-",           //Prefix string attached to the class of every element generated by the plugin       
      animation: "slide",            //Select your animation type, "fade" or "slide"
      easing: "easeInOutExpo",       //Determines the easing method used in jQuery transitions. jQuery easing plugin is supported!
      direction: "horizontal",       //Select the sliding direction, "horizontal" or "vertical"       
      animationLoop: true,           //Should the animation loop? If false, directionNav will received "disable" classes at either end  
      slideshowSpeed: 7000,          //Set the speed of the slideshow cycling, in milliseconds
      animationSpeed: 600,           //Set the speed of animations, in milliseconds       
      pauseOnHover: true,            //Pause the slideshow when hovering over slider, then resume when no longer hovering
      useCSS: true,                  //Slider will use CSS3 transitions if available
      touch: true,                   //Allow touch swipe navigation of the slider on touch-enabled devices
      video: true,                   //If using video in the slider, will prevent CSS3 3D Transforms to avoid graphical glitches
      controlNav: true,              //Create navigation for paging control of each clide? Note: Leave true for manualControls usage
      directionNav: true,            //Create navigation for previous/next navigation? (true/false)
                  
      // Callback API               
      before: function(slider){
        $('.flex-caption').stop().fadeOut('slow');
      },           //Callback: function(slider) - Fires asynchronously with each slider animation
      after: function(slider){
        $('.flex-caption').fadeIn('slow');
      }           //Callback: function(slider) - Fires after each slider animation completes        
    });  
  }

  if ($('.flexslider3').length && jQuery()) {
     $('.features-slider').flexslider({
        namespace: "feat-slide-",       
        animation: "slide",
        controlNav: false,
        directionNav: false, 
        animationLoop: false,        
        slideshow: false,        
        itemMargin: 20,
        asNavFor: '.flexslider3'
      });
    $('.flexslider3').flexslider({
      namespace: "flex3-",           //Prefix string attached to the class of every element generated by the plugin       
      animation: "fade",             //Select your animation type, "fade" or "slide"
      easing: "easeInOutExpo",       //Determines the easing method used in jQuery transitions. jQuery easing plugin is supported!
      direction: "horizontal",       //Select the sliding direction, "horizontal" or "vertical"       
      animationLoop: true,           //Should the animation loop? If false, directionNav will received "disable" classes at either end  
      slideshow: true,
      slideshowSpeed: 7000,          //Set the speed of the slideshow cycling, in milliseconds
      animationSpeed: 1000,          //Set the speed of animations, in milliseconds       
      pauseOnHover: true,            //Pause the slideshow when hovering over slider, then resume when no longer hovering
      useCSS: false,                 //Slider will use CSS3 transitions if available
      touch: true,                   //Allow touch swipe navigation of the slider on touch-enabled devices
      video: true,                   //If using video in the slider, will prevent CSS3 3D Transforms to avoid graphical glitches
      controlNav: false,             //Create navigation for paging control of each clide? Note: Leave true for manualControls usage
      directionNav: false,           //Create navigation for previous/next navigation? (true/false)
      sync: '.features-slider',

      // Callback API               
      start: function(slider){
        $('#slider').removeClass('loading').stop();
      },
      before: function(slider){             
       
      },                          //Callback: function(slider) - Fires asynchronously with each slider animation
      after: function(slider){
        
      }                           //Callback: function(slider) - Fires after each slider animation completes        
    });  
  }

  // 03 Project Slider
  if ($('#project-slider').length && jQuery()) {
    $('#project-slider').flexslider({
      namespace: 'project-slider-',   //Prefix string attached to the class of every element generated by the plugin
      animation: 'slide',             //Select your animation type, "fade" or "slide"
      slideshowSpeed: 7000,           //Set the speed of the slideshow cycling, in milliseconds
      animationSpeed: 600,            //Set the speed of animations, in milliseconds   
      controlNav: false,              //Create navigation for paging control of each clide? Note: Leave true for manualControls usage
      animationLoop: true,            //Should the animation loop? If false, directionNav will received "disable" classes at either end
      slideshow: true,                //Setup a slideshow for the slider to animate automatically.
      smoothHeight: false             //Animate the height of the slider smoothly for slides of varying height.
    }); 
  }

  // 04 Widget Slide
  if ($('.widget-slide').length && jQuery()) {
    $('.widget-slide').flexslider({
      namespace: "widget-slide-",     //Prefix string attached to the class of every element generated by the plugin
      animation: "slide",             //Select your animation type, "fade" or "slide"
      slideshowSpeed: 7000,           //Set the speed of the slideshow cycling, in milliseconds
      animationSpeed: 600,            //Set the speed of animations, in milliseconds   
      animationLoop: true,            //Should the animation loop? If false, directionNav will received "disable" classes at either end
      controlNav: false,              //Create navigation for paging control of each clide? Note: Leave true for manualControls usage
      smoothHeight: true,            //Animate the height of the slider smoothly for slides of varying height.
      useCSS: true,                   //Slider will use CSS3 transitions if available
      maxItems: 1                     //Maximum number of carousel items that should be visible.
    });
  }

  // 05 Post Slider
  if ($('.post-slider').length && jQuery()) {
    $('.post-slider').flexslider({
      namespace: "post-slider-",      //Prefix string attached to the class of every element generated by the plugin
      animation: "slide",             //Select your animation type, "fade" or "slide"
      slideshowSpeed: 7000,           //Set the speed of the slideshow cycling, in milliseconds
      animationSpeed: 600,            //Set the speed of animations, in milliseconds   
      animationLoop: true,            //Should the animation loop? If false, directionNav will received "disable" classes at either end
      controlNav: false,              //Create navigation for paging control of each clide? Note: Leave true for manualControls usage
      useCSS: true,                   //Slider will use CSS3 transitions if available
      smoothHeight: false,            //Animate the height of the slider smoothly for slides of varying height.
      maxItems: 1
    });
  }

  // 06 Testimonial Slider
  if ($('#client-testimonial').length && jQuery()) {
      $('#client-testimonial').flexslider({
      namespace: "testimonial-",      //Prefix string attached to the class of every element generated by the plugin
      animation: "fade",              //Select your animation type, "fade" or "slide"
      slideshowSpeed: 7000,           //Set the speed of the slideshow cycling, in milliseconds
      animationSpeed: 600,            //Set the speed of animations, in milliseconds   
      animationLoop: true,            //Should the animation loop? If false, directionNav will received "disable" classes at either end
      controlNav: false,              //Create navigation for paging control of each clide? Note: Leave true for manualControls usage
      smoothHeight: true,             //Animate the height of the slider smoothly for slides of varying height.
      useCSS: true,                   //Slider will use CSS3 transitions if available
      maxItems: 1                     //Maximum number of carousel items that should be visible.
    });
  }

  });

  // 07 Work Carousel & Blog Carousel

  if ($('.works-carousel, .blog-carousel, .works-carousel2, .blog-carousel2, .works-carousel3, .logo-carousel').length && !$('html').hasClass('oldie') && jQuery()) {    

    var twocolWorks = { 
      responsive: false,
      width: '100%', 
      height: 'variable',  
      auto: false,
      circular  : false,
      infinite  : false,
      prev : {
        button    : ".works3-prev",
        key     : "left"
      },
      next : {
        button    : ".works3-next",
        key     : "right"
      },
      scroll : {
        easing: "easeInOutExpo"
      },
      swipe: {
        onMouse: true,
        onTouch: true
      },
      items: {  
        visible: {
          min: 1,
          max: 2
        }
      }
    }; 

    var threecolWorks = { 
      responsive: false,
      width: '100%',
      height: 'variable',   
      auto: false,
      circular  : false,
      infinite  : false,
      prev : {
        button    : ".works-prev",
        key     : "left"
      },
      next : {
        button    : ".works-next",
        key     : "right"
      },
      scroll : {
        easing: "easeInOutExpo"
      },
      swipe: {
        onMouse: true,
        onTouch: true
      },
      items: {  
        visible: {
          min: 1,
          max: 3
        }
      }
    }; 

    var threecolBlog = { 
      responsive: false,
      width: '100%',
      height: 'variable',   
      auto: false,
      circular  : false,
      infinite  : false,
      prev : {
        button    : ".blog-prev",
        key     : "left"
      },
      next : {
        button    : ".blog-next",
        key     : "right"
      },
      scroll : {
        easing: "easeInOutExpo"
      },
      swipe: {
        onMouse: true,
        onTouch: true
      },
      items: {  
        visible: {
          min: 1,
          max: 3
        }
      }
    }; 

    var fourcolWorks = {
      responsive: false,
      width: '100%', 
      height: 'variable',  
      auto: false,
      circular  : false,
      infinite  : false,
      prev : {
        button    : ".works2-prev",
        key     : "left"
      },
      next : {
        button    : ".works2-next",
        key     : "right"
      },
      scroll : {
        easing: "easeInOutExpo"
      },
      swipe: {
        onMouse: true,
        onTouch: true
      },
      items: {      
        visible: {
          min: 1,
          max: 4
        }
      }
    };

    var fourcolBlog = {
      responsive: false,
      width: '100%',  
      height: 'variable', 
      auto: false,
      circular  : false,
      infinite  : false,
      prev : {
        button    : ".blog2-prev",
        key     : "left"
      },
      next : {
        button    : ".blog2-next",
        key     : "right"
      },
      scroll : {
        easing: "easeInOutExpo"
      },
      swipe: {
        onMouse: true,
        onTouch: true
      },
      items: {      
        visible: {
          min: 1,
          max: 4
        }
      }
    };

    var fourcolLogo = {
      responsive: false,
      width: '100%',   
      height: 'variable',
      auto: false,
      circular  : false,
      infinite  : false,
      prev : {
        button    : ".logo-prev",
        key     : "left"
      },
      next : {
        button    : ".logo-next",
        key     : "right"
      },
      scroll : {
        easing: "easeInOutExpo"
      },
      swipe: {
        onMouse: true,
        onTouch: true
      },
      items: {      
        visible: {
          min: 1,
          max: 4
        }
      }
    };

   
    $(window).load(function() {  

    if ($('.works-carousel').length && jQuery()) {  
      $('.works-carousel').carouFredSel(threecolWorks);
    }

    if ($('.blog-carousel').length && jQuery()) {
      $('.blog-carousel').carouFredSel(threecolBlog);
    }

    if ($('.works-carousel2').length && jQuery()) {
      $('.works-carousel2').carouFredSel(fourcolWorks);
    }

    if ($('.blog-carousel2').length && jQuery()) {
      $('.blog-carousel2').carouFredSel(fourcolBlog);
    }

    if ($('.logo-carousel').length && jQuery()) {
      $('.logo-carousel').carouFredSel(fourcolLogo);
    }

    if ($('.works-carousel3').length && jQuery()) {
      $('.works-carousel3').carouFredSel(twocolWorks);
    }

    });

  function carouselUpdate() {

    if ($('.works-carousel').length && jQuery()) {  
      $('.works-carousel').trigger("configuration", threecolWorks);
    }
    if ($('.blog-carousel').length && jQuery()) { 
      $('.blog-carousel').trigger("configuration", threecolBlog);   
    }
    if ($('.works-carousel2').length && jQuery()) { 
      $('.works-carousel2').trigger("configuration", fourcolWorks);
    }
    if ($('.blog-carousel2').length && jQuery()) { 
      $('.blog-carousel2').trigger("configuration", fourcolBlog);   
    }
    if ($('.works-carousel3').length && jQuery()) { 
      $('.works-carousel3').trigger("configuration", twocolWorks);
    }
    if ($('.logo-carousel').length && jQuery()) { 
      $('.logo-carousel').trigger("configuration", fourcolLogo);
    }
  }

  var resizeUpdate;

  $(window).resize(function() {
      clearTimeout(resizeUpdate);
      resizeUpdate = setTimeout(carouselUpdate, 100);
  });  
  

  }

  // 
  if ($('.works-carousel, .blog-carousel, .works-carousel2, .blog-carousel2, .works-carousel3, .logo-carousell').length && $('html').hasClass('oldie') && jQuery()) {

    var twocolWorks = { 
      responsive: false,
      width: '100%', 
      height: 'variable',  
      auto: false,
      circular  : false,
      infinite  : false,
      prev : {
        button    : ".works3-prev",
        key     : "left"
      },
      next : {
        button    : ".works3-next",
        key     : "right"
      },
      scroll : {
        easing: "easeInOutExpo"
      },
      swipe: {
        onMouse: true,
        onTouch: true
      },
      items: {  
        visible: {
          min: 1,
          max: 2
        }
      }
    }; 

    var threecolWorks = { 
      responsive: true,
      width: '100%',   
      auto: false,
      circular  : false,
      infinite  : false,
      prev : {
        button    : ".works-prev",
        key     : "left"
      },
      next : {
        button    : ".works-next",
        key     : "right"
      },
      scroll : {
        easing: "easeInOutExpo"
      },
      swipe: {
        onMouse: true,
        onTouch: true
      },
      items: {  
        width: 300,
        visible: {
          min: 1,
          max: 3
        }
      }
    }; 

    var threecolBlog = {
      responsive: true,
      width: '100%',   
      auto: false,
      circular  : false,
      infinite  : false,
      prev : {
        button    : ".blog-prev",
        key     : "left"
      },
      next : {
        button    : ".blog-next",
        key     : "right"
      },
      scroll : {
        easing: "easeInOutExpo"
      },     
      items: {  
        width: 300,    
        visible: {
          min: 1,
          max: 3
        }
      }
    };

    var fourcolWorks = {
      responsive: true,
      width: '100%', 
      height: 'variable',  
      auto: false,
      circular  : false,
      infinite  : false,
      prev : {
        button    : ".works2-prev",
        key     : "left"
      },
      next : {
        button    : ".works2-next",
        key     : "right"
      },
      scroll : {
        easing: "easeInOutExpo"
      },     
      items: {    
        width: 220,  
        visible: {
          min: 1,
          max: 4
        }
      }
    };

    var fourcolBlog = {
      responsive: true,
      width: '100%',   
      auto: false,
      circular  : false,
      infinite  : false,
      prev : {
        button    : ".blog2-prev",
        key     : "left"
      },
      next : {
        button    : ".blog2-next",
        key     : "right"
      },
      scroll : {
        easing: "easeInOutExpo"
      },     
      items: {  
        width: 220,    
        visible: {
          min: 1,
          max: 4
        }
      }
    };

    var fourcolLogo = {
      responsive: true,
      width: '100%',   
      auto: false,
      circular  : false,
      infinite  : false,
      prev : {
        button    : ".logo-prev",
        key     : "left"
      },
      next : {
        button    : ".logo-next",
        key     : "right"
      },
      scroll : {
        easing: "easeInOutExpo"
      },      
      items: {   
        width: 235,   
        visible: {
          min: 1,
          max: 4
        }
      }
    };

    var fourcolStream = {
      responsive: true,
      width: '100%',
      height: '115px',
      auto: false,
      circular  : false,
      infinite  : false,
      prev : {
        button    : ".photostream-prev",
        key     : "left"
      },
      next : {
        button    : ".photostream-next",
        key     : "right"
      },
      scroll : {
        easing: "easeInOutExpo"
      },
      swipe: {
        onMouse: true,
        onTouch: true
      },
      items: {      
        visible: {
          min: 3         
        }
      }
    };
    

    $(window).load(function() {      

     if ($('.works-carousel').length && jQuery()) {  
      $('.works-carousel').carouFredSel(threecolWorks);
    }

    if ($('.blog-carousel').length && jQuery()) {
      $('.blog-carousel').carouFredSel(threecolBlog);
    }

    if ($('.works-carousel2').length && jQuery()) {
      $('.works-carousel2').carouFredSel(fourcolWorks);
    }

    if ($('.blog-carousel2').length && jQuery()) {
      $('.blog-carousel2').carouFredSel(fourcolBlog);
    }

    if ($('.logo-carousel').length && jQuery()) {
      $('.logo-carousel').carouFredSel(fourcolLogo);
    }

    if ($('.works-carousel3').length && jQuery()) {
      $('.works-carousel3').carouFredSel(twocolWorks);
    }
       
    });  
  
  }

  // End Work Carousel & Blog Carousel

  // 08 Camera Slider
  if ($('#cameraslider').length && jQuery()) {
    $('#cameraslider').camera({
      navigation: true,         //if true the navigation button (prev, next and play/stop buttons) will be visible, if false they will be always hidden
      thumbnails: false,        //true, false
      pagination: true,         //true, false
      playPause: true,          //true or false, to display or not the play/pause buttons
      pauseOnClick: true,       //true, false. It stops the slideshow when you click the sliders
      loader: 'pie',            //pie, bar, none (even if you choose "pie", old browsers like IE8- can't display it... they will display always a loading bar)
      loaderColor: '#eeeeee',
      loaderBgColor: '#222222',
      loaderOpacity: .8,        //0, .1, .2, .3, .4, .5, .6, .7, .8, .9, 1
      loaderPadding: 2,         //how many empty pixels you want to display between the loader and its background
      loaderStroke: 7,          //the thickness both of the pie loader and of the bar loader. Remember: for the pie, the loader thickness must be less than a half of the pie diameter
      pieDiameter: 38,        
      piePosition: 'rightTop',  //'rightTop', 'leftTop', 'leftBottom', 'rightBottom'
      cols: 6,
      rows: 4,
      slicedCols: 12,           //if 0 the same value of cols
      slicedRows: 8,            //if 0 the same value of rows
      slideOn: 'random',        //next, prev, random: decide if the transition effect will be applied to the current (prev) or the next slide
      time: 7000,               //milliseconds between the end of the sliding effect and the start of the nex one
      transPeriod: 1500         //length of the sliding effect in milliseconds
    });
  }

  // 09 Content Slider
  if ($('#da-slider').length && jQuery()) {
    $('#da-slider').cslider({
      bgincrement : 0,
      autoplay: true,
      interval  : 4000 
    });
  }

  // 10 Responsive Dropdown Menu
    var $menu_select = $("<select />"); 

    $("<option />", {"selected": "selected", "value": "", "text": "Site Navigation"}).appendTo($menu_select);
    $menu_select.appendTo("#main-nav");
    $("#main-nav ul li a").each(function(){
      var menu_url = $(this).attr("href");
      var menu_text = $(this).text();
      if ($(this).parents("li").length == 2) { menu_text = '- ' + menu_text; }
      if ($(this).parents("li").length == 3) { menu_text = "-- " + menu_text; }
      if ($(this).parents("li").length > 3) { menu_text = "--- " + menu_text; }
      $("<option />", {"value": menu_url, "text": menu_text}).appendTo($menu_select)
    })

    field_id = "#main-nav select";
    $(field_id).change(function()
    {
       value = $(this).attr('value');
       window.location = value; 
    });     
      
  // 11 Tipsy
  $('.tooltips').tipsy({               
    delayIn: 50,                // delay before showing tooltip (ms)
    delayOut: 100,              // delay before hiding tooltip (ms)
    fade: true,                 // fade tooltips in/out?
    fallback: '',               // fallback text to use when no tooltip text
    gravity: $.fn.tipsy.autoNS, // gravity
    html: false,                // is tooltip content HTML?
    live: false,                // use live event support?
    offset: 0,                  // pixel offset of tooltip from element
    opacity: 0.8,               // opacity of tooltip
    title: 'title',             // attribute/callback containing tooltip text
    trigger: 'hover'            // how tooltip is triggered - hover | focus | manual
  });
  $('.tooltips-team').tipsy({
    delayIn: 100,               // delay before showing tooltip (ms)
    delayOut: 100,              // delay before hiding tooltip (ms)
    fade: true,                 // fade tooltips in/out?
    fallback: '',               // fallback text to use when no tooltip text
    gravity: 's',               // gravity
    html: true,                 // is tooltip content HTML?
    live: false,                // use live event support?
    offset: -25,                // pixel offset of tooltip from element
    opacity: 0.8,               // opacity of tooltip
    title: 'title',             // attribute/callback containing tooltip text
    trigger: 'hover'            // how tooltip is triggered - hover | focus | manual
  });
 
  // 12 Works Zoomer
  if ($('.works-item').length && jQuery()) {
    
    //move the image in pixel
    var move = -8;
     
    //zoom percentage, 1.08 =108%
    var zoom = 1.08;

    $('.works-item').hover(function() {
         
      //Set the width and height according to the zoom percentage
      
      var workWidth;

      if( $(window).width() < 480 ) {
        workWidth = 300;
      } else if( $(window).width() < 768 ) {
        workWidth = 240;
      } else if( $(window).width() < 960 ) {
        workWidth = 187;
      } else {
        workWidth = 235;
      }

      var workHeight;
      if( $(window).width() < 480 ) {
        workHeight = 300;
      } else if( $(window).width() < 768 ) {
        workHeight = 240;
      } else if( $(window).width() < 960 ) {
        workHeight = 187;
      } else {
        workHeight = 235;
      }

      width = workWidth * zoom;
      height = workHeight * zoom;
       
      //Display the caption
      $(this).find('div.works-overlay').stop(false,true).show().animate({'width':width, 'height':height, 'top':move, 'left':move}, {duration:100});

        //Move and zoom the image
      $(this).find('img').stop(false,true).animate({'width':width, 'height':height, 'top':move, 'left':move}, {duration:100});
           
      },
      function() {
           //Hide the caption
          $(this).find('div.works-overlay').stop(false,true).animate({'width':$('.works-item').width(), 'height':$('.works-item').height(), 'top':'0', 'left':'0'}, {duration:100}).hide();

          //Reset the image
          $(this).find('img').stop(false,true).animate({'width':$('.works-item').width(), 'height':$('.works-item').height(), 'top':'0', 'left':'0'}, {duration:100});           
      }); 

    function zoomWork() {

    var workWidth;

      if( $(window).width() < 480 ) {
        workWidth = 299;
      } else if( $(window).width() < 768 ) {
        workWidth = 239;
      } else if( $(window).width() < 960 ) {
        workWidth = 186;
      } else {
        workWidth = 234;
      }

      var workHeight;
      if( $(window).width() < 480 ) {
        workHeight = 299;
      } else if( $(window).width() < 768 ) {
        workHeight = 239;
      } else if( $(window).width() < 960 ) {
        workHeight = 186;
      } else {
        workHeight = 234;
      }

    width = workWidth;
    height = workHeight;

    $('.works-item').find('img, div.works-overlay').animate({'width':width, 'height':height});

    };

    var resizeTimer;

    $(window).resize(function() {
        clearTimeout(resizeTimer);
        resizeTimer = setTimeout(zoomWork, 100);
    });
  }
  // End Works Zoomer

  // 13 Skill Bars
  if ($('.skillbar').length && jQuery()) {
    var didResize  = true;

    $(window).resize(function () {
      
      didResize = true;       

    });

    setInterval(function() {
    if(didResize) {
      didResize = false;

      // Skills Bar Animation
      $('.skillbar').each(function(){
        var t = $(this),
        skillb = $('.skillbars').width(),
        
        dataperc = t.attr('data-perc'),
        dataperc2 = dataperc/100,
        barperc = Math.round(skillb*dataperc2);
        t.find('.bar').animate({width:barperc}, 500);
        
        function perc() {           
            t.find('.perc').text(dataperc+'%');
        }
        perc();
        setInterval(perc, 0);
      });
      }
    }, 250);
  }

  // 14 Fancybox
  if ($('.fancybox').length && jQuery()) {
    $(".fancybox").fancybox({
     'autoScale' : true,
      'transitionIn'  : 'elastic',
      'transitionOut' : 'elastic'
    });  
  } 

  // 15 Google Map for Contact 1
  if ($('#map-canvas').length && jQuery()) {

      $("#map-canvas").gMap({
      panControl: true,             //The pan control displays buttons for panning the map.
      scaleControl: true,           //The scale control displays a map scale element.
      scrollwheel: false,           //Set to false to disable zooming with your mouses scrollwheel.
      latitude: 34.057211,          //Point on which the viewport will be centered.
      longitude: -118.309906,       //Point on which the viewport will be centered
      controlsPositions: {          //Positions of default controls.
        zoom: google.maps.ControlPosition.TOP_RIGHT,
        pan: google.maps.ControlPosition.TOP_RIGHT,
        streetView: google.maps.ControlPosition.TOP_RIGHT,
        scale: google.maps.ControlPosition.TOP_RIGHT
      },
      markers: [{                   //List of points to be marked on the map
        latitude: 34.057211,        //Point on the map where the marker will be drawn
        longitude: -118.304506,     //Point on the map where the marker will be drawn
        html: 'OmniBiz - Responsive HTML Template<br><a class="button solid" href="#">Buy Now at ThemeForest</a>'
        /* Content that will be shown within the info window for this marker. If empty no info window will be shown when the user clicks the marker.  */ 
      }], 
      icon: {                       //Subset of properties for defining a custom marker image for all markers.
        image: 'img/gmap_pin.png',  //Full path to a image that indicates the marker on the map.
        iconsize: [44, 54],         //A simple array of integer values for width and height valid for "image".
        iconanchor: [22, 54],       //The pixel coordinate relative to the top left corner of the icon image at which this icon is anchored to the map.
        infowindowanchor: [22, 0]   //The pixel coordinate relative to the top left corner of the icon image at which the info window is anchored to this icon.
      },          
      zoom: 16                      //Zoom value from 1 to 19 where 19 is the greatest and 1 the smallest.
      });   
  }

  // 16 Google Map for Contact 2
  if ($('#map-canvas2').length && jQuery()) {

    $("#map-canvas2").gMap({     
      panControl: true,             //The pan control displays buttons for panning the map.
      scaleControl: true,           //The scale control displays a map scale element.
      scrollwheel: false,           //Set to false to disable zooming with your mouses scrollwheel.
      latitude: 34.057211,          //Point on which the viewport will be centered.
      longitude: -118.304506,       //Point on which the viewport will be centered
      markers: [{                   //List of points to be marked on the map
        latitude: 34.057211, 
        longitude: -118.304506,
        html: 'OmniBiz - Responsive HTML Template<br><a class="button solid" href="#">Buy Now at ThemeForest</a>' 
        /* Content that will be shown within the info window for this marker. If empty no info window will be shown when the user clicks the marker.  */   
      }],
      icon: {                       //Subset of properties for defining a custom marker image for all markers.
        image: 'img/gmap_pin.png',  //Full path to a image that indicates the marker on the map.
        iconsize: [44, 54],         //A simple array of integer values for width and height valid for "image".
        iconanchor: [22, 54],       //The pixel coordinate relative to the top left corner of the icon image at which this icon is anchored to the map.
        infowindowanchor: [22, 0]   //The pixel coordinate relative to the top left corner of the icon image at which the info window is anchored to this icon.
      },          
      zoom: 16                      //Zoom value from 1 to 19 where 19 is the greatest and 1 the smallest.
    });

  }

  // 17 Widget Tabs
  if ($('.widget-tabs').length && jQuery()) {
    $('.widget-tabs').tabs({
      fx: { 
          opacity: 'toggle',
          duration:'fast'
      }
    });
  }
  
  // 18 Responsive Video
  if ($('.video-wrapper').length && jQuery()) {
    $('.video-wrapper').fitVids();
  }

  // 19 zFlickrFeed
  if ($('#flickrImages').length && jQuery()) {
    $('#flickrImages').flickrfeed(
      '52617155@N08',                 // A Flickr user ID. Can be used in conjuction with the tags option.
      '',                             // A comma separated list of tags to search. Can be used in conjuction with the user ID option.
    {                                 // Optional settings for the plug-in (see below).
      limit: 8,                       // The number of photos to return.
      header: false,                  // If true, includes the header section containing the feed title and link.
      imagesize: 'square',            // Specifies the size of image: square | thumbnail | small | medium
      titletag: 'h4',                 // Specifies the HTML tag for the photo title.
      title: false,                   // If true, includes the photo title section.
      date: false                     // If true, includes the published date section.
    });
  }
  

  // 20 Tweetable
  if ($('#tweets').length && jQuery()) {
    $('#tweets').tweetable({
      limit: 2,                       // Number of tweets to show
      username: 'envato',             // @username tweets to display
      time: true,                     // Display date
      rotate: false,                  // Rotate tweets
      speed: 5000,                    // Speed of rotation
      replies: true,                  // Filter out @replys
      position: 'append',             // Append position
      failed: "No tweets available",  // Twitter stream unavailable text
      html5: true,                    // HTML5 Support
      retweets: true,                 // Show retweets
      onComplete: function($ul) {     // On complete callback
        $('time').timeago();
      }    
    }); 
  }  

  // 21 Isotope Filtering
  if($('.portfolio-items').length && jQuery()) {
   
  $(window).load(function() {  
  
    var $container = $('.portfolio-items');
      $container.isotope({
      itemSelector : '.portfolio-items .columns',
      animationEngine : 'css',
      animationOptions: {
        duration: 200,
        easing: 'easeInOutExpo',
        queue: false
      }
    });
     
    $(window).resize(function() {
      var $container = $('.portfolio-items');
        $container.isotope({
        itemSelector : '.portfolio-items .columns',
        animationEngine : 'css',
        animationOptions: {
          duration: 200,
          easing: 'easeInOutExpo',
          queue: false
        }
      });
    });  
      
    // filter items when filter link is clicked
    $('#portfolio-nav a').click(function(){
                       //alert("CLICK")
        var selector = $(this).attr('data-filter');
        $container.isotope({ filter: selector });
        
        $("#portfolio-nav li").removeClass("current");
        $(this).closest("li").addClass("current");
        
        return false;
    });

  });
  }

  // 22 Tabs & Accordioin

  $('#tabs').tabs().addClass('ui-tabs-vertical');   
  
  $('#accordion').accordion({
    heightStyle: "content",
    autoHeight: false
  });
 
  $('#toggle-accordion').accordion({
    heightStyle: "content",
    collapsible: true,
    autoHeight: false

  });  
 
  $('.tabs-horizontal').tabs({
    fx: { 
        opacity: 'toggle',
        duration:'fast'
    }
  });

  // 23 Info Box
  $('<button class="info-close">×</button>').prependTo('.info-box');$('.info-close').click(function(){
    $(this).parent(".info-box").fadeOut(200);
  });

  
  // 24 Portfolio Image Hover 
  $('.portfolio-items li.columns').hover(function () {
      $(this).find('span.portfolio-overlay').stop(true,true).animate({opacity: 1, top: '0', left: '0'}, 200 );
    }, function () {
      $(this).find('span.portfolio-overlay').stop(true,true).animate({opacity: 0, top: '+50%', left: '+50%'}, 200 );
    }
  );
  
  // 25 Blog Masonry
  if($('.blog-masonry').length && jQuery()) {

    $(window).load(function() {  
  
    var $container = $('.blog-masonry');
      $container.isotope({
        itemSelector : '.blog-masonry .columns',
        animationEngine : 'jquery',
        animationOptions: {
          duration: 400,
          easing: 'easeInOutExpo',
          queue: false
        }
      });
     
    $(window).resize(function() {
      var $container = $('.blog-masonry');
        $container.isotope({
          itemSelector : '.blog-masonry .columns',
          animationEngine : 'jquery',
          animationOptions: {
            duration: 400,
            easing: 'easeInOutExpo',
            queue: false
          }
        });
      });
    });
  }

  // 26 jQuery Countdown & Easy Pie Chart
  if($('#timer').length && jQuery()) {
 
  var liftOff = new Date("January 1, 2013");  // change your date here

  $('#timer').countdown({ 

    until:liftOff, 

    layout: '<ul class="timer-chart">{d<}<li class="chart"><div class="percentage days" data-percent="{dn}"><span class="days">{dn}</span><span class="perc-overlay"></span></div><div class="label">{dl}</div></li>{d>}' + '{h<}<li class="chart"><div class="percentage hours" data-percent="" data-value="{hn}"><span class="hours">{hn}</span><span class="perc-overlay"></span></div><div class="label">{hl}</div></li>{h>}' + '{m<}<li class="chart"><div class="percentage minutes" data-percent="" data-value="{mn}"><span class="minutes">{mn}</span><span class="perc-overlay"></span></div> <div class="label">{ml}</div></li>{m>}' + '{s<}<li class="chart"><div class="percentage seconds" data-percent="" data-value="{sn}"><span class="seconds">{sn}</span><span class="perc-overlay"></span></div><div class="label">{sl}</div></li>{s>}</ul>', //do not modify this unless you know what you're doing :)
  
    onTick: function() {                

    // Add Easy Pie Chart
      $('.percentage').easyPieChart({   // easyPieChart Options
        size: 150,                      // Pie Size
        animate: false,                 // animation (set this to false or else the countdown will freeze)        
        lineWidth: 2,                   // the pie line width
        lineCap: 'round',               // the pie line cap ('round' or 'butt')
        scaleColor: '#cccccc',          // the scale background color
        trackColor: '#f6f6f6',          // the track background color
        barColor: '#49abcf'             // the bar (main) color
      });

    // Update Hours Data  
      $('.percentage.hours').each(function() {
         
            var percentData = $('.percentage.hours').data('value');
            var newData = Math.floor(percentData * 4.666666666666667);
            //console.log(newData);
            $('.percentage.hours').data('easyPieChart').update(newData);
        
      });

    // Update Minutes Data
      $('.percentage.minutes').each(function() {
         
            var percentData = $('.percentage.minutes').data('value');
            var newData = Math.floor(percentData * 1.666666666666667);  
            //console.log(newData);
            $('.percentage.minutes').data('easyPieChart').update(newData);
        
      });

    // Update Seconds Data
      $('.percentage.seconds').each(function() {
        
            var percentData = $('.percentage.seconds').data('value');
            var newData = Math.floor(percentData * 1.666666666666667);  
            //console.log(newData);
            $('.percentage.seconds').data('easyPieChart').update(newData);
        
      });

    }

  }); 
  }

  // 27 Subscribe Form Validation
  if($('#subscribe-form').length && jQuery()) {
  
    $('form#subscribe-form').submit(function() {

      $('form#subscribe-form .error').remove();

      var hasError = false;

      $('.required').each(function() {
        if(jQuery.trim($(this).val()) == '') {
          var labelText = $(this).prev('label').text();
          $(this).parent().append('<p class="error">Please enter your Email'+labelText+'</span>');
          $(this).addClass('inputError');
          hasError = true;
        } else if($(this).hasClass('email')) {
          var emailReg = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;
          if(!emailReg.test(jQuery.trim($(this).val()))) {
            var labelText = $(this).prev('label').text();
            $(this).parent().append('<p class="error">Please enter a valid email address'+labelText+'</span>');
            $(this).addClass('inputError');
            hasError = true;
          }
        }
      });

      if(!hasError) {
        $('form#subscribe-form input.submit').fadeOut('normal', function() {
          $(this).parent().append('');
        });
        var formInput = $(this).serialize();
        $.post($(this).attr('action'),formInput, function(data){
          $('form#subscribe-form').slideUp("fast", function() {
            $(this).before('<p class="success">Thank you for your subscription!</p>');
          });
        });
      }

      return false;

    });  
  }

  //28 Contact Form Validation
  if($('#contact-form').length && jQuery()) {
    $('form#contact-form').submit(function() {

      $('form#contact-form .info-box.red').remove();

      var hasError = false;

      $('.required').each(function() {
        if(jQuery.trim($(this).val()) == '') {
          var labelText = $(this).prev('label').text();
          $(this).parent().append('<div class="info-box red">Please Enter Your '+labelText+'</span>');
          $(this).addClass('inputError');
          hasError = true;
        } else if($(this).hasClass('email')) {
          var emailReg = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;
          if(!emailReg.test(jQuery.trim($(this).val()))) {
            var labelText = $(this).prev('label').text();
            $(this).parent().append('<div class="info-box red">Please Enter a Valid Email Address</span>');
            $(this).addClass('inputError');
            hasError = true;
          }
        }
      });

      if(!hasError) {
        $('form#contact-form button.submit').fadeOut('fast', function() {
          $(this).parent().append('');
        });
        var formInput = $(this).serialize();
        $.post($(this).attr('action'),formInput, function(data){
          $('form#contact-form').slideUp("fast", function() {
            $(this).before('<div class="info-box green">Thank You for Your Message!');
          });
        });
      }

      return false;

    });  
  }

  //29 Superfish Menu

  $('ul.sf-menu').superfish({
    animationOpen : {opacity:'show', height:'show'},  // an object equivalent to first parameter of jQuery’s .animate() method 
    animationClose: {height:'hide', opacity:'hide'},  // an object equivalent to first parameter of jQuery’s .animate() method 
    speed   : 100,                                    // speed of the animation. 'true' or 'false' or numbers (in milliseconds)
    delay   : 200,                                    // the delay in milliseconds that the mouse can remain outside a submenu without it closing
    autoArrows:  false,                               // if true, arrow mark-up generated automatically
    dropShadows: false,                               // completely disable drop shadows by setting this to false  
    pathLevels  : 2                                   // the number of levels of submenus that remain open or are restored using pathClass
  });

}); //End Document Ready